name: GitHub Actions Demo
run-name: Deployment initialized by ${{ github.actor }}

on:
  workflow_dispatch:
  push:
    branches:
      - main
      
jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up SSH
              uses: webfactory/ssh-agent@v0.5.3
              with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
                ec2-host: ${{ secrets.EC2_HOST }}
               
            - name: Deploy to EC2
              run: |
                scp index.html ubuntu@${{ secrets.EC2_HOST }}:/var/www/html/index.html

            - name: Restart Nginx
              run: |
                ssh ubuntu@${{ secrets.EC2_HOST }} "sudo systemctl restart nginx"

            - name: Deployment status
              run: |
                echo "Deployment successful"