name: GitHub Actions Demo
run-name: Deployment initialized by ${{ github.actor }}

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Copying files to remote server
              uses: appleboy/scp-action@v0.1.7
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.USERNAME }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                source: "index.html"
                target: "/home/ubuntu"
               
            - name: Deploying Application
              uses: appleboy/ssh-action@v1
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.USERNAME }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                script: |
                  sudo mv index.html /var/www/html
                  sudo systemctl restart nginx

            - run: echo "Deployment successful"