name: GitHub Actions Demo
run-name: Deployment initialized by ${{ github.actor }}

on:
  workflow_dispatch:
  push:
    branches:
      - main
      
jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: SSH setup
              uses: appleboy/ssh-action@v1
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.USERNAME }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                script: |
                  scp index.html ${{ secrets.USERNAME }}@${{ secrets.EC2_HOST }}:/var/www/html/index.html
                  ssh ${{ secrets.USERNAME }}@${{ secrets.EC2_HOST }} "sudo systemctl restart nginx"

            - name: Deployment status
              run: |
                echo "Deployment successful"
